# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 01348a72a37b314291764283055056ae697939cc9b66c55529d75a1172f2c105b16d1da3692abf54c8c57ebb4a60324a126c33207a0114ef8fd8806b93172979

test:
  secret_key_base: b381f2a82bd71c5b37753077f559ad3a4d79132df56c600db2d69f03b619d15c167f78fab74026e9b75afbffa8def456de11090834a556e8da9755fc773dfaa8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
